name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

#      - name: Test
#        env:
#          # These secrets will need to be configured for the repository:
#        run: go test -v ./...